- name: Install Linux packages
  apt:
    pkg:
      - python-dev
      - libbluetooth-dev
      - libcap2-bin
      - git
      - python3-pip
      - python-setuptools
      - logrotate

- name: Determine the path to python3
  command: "which python3"
  register: python3_path
  changed_when: false

- name: Fail if we can't get the python3 path
  fail:
    msg: "Unable to determine the path to python3 {{ python3_path }}"
  when: python3_path.rc != 0

- name: Get full path to python3
  stat:
    path: "{{ python3_path.stdout }}"
  register: python3_stat
  changed_when: false

- name: Allow python raw socket access
  shell: "setcap 'cap_net_raw,cap_net_admin+eip' {{ python3_stat.stat.lnk_source }}"
  changed_when: false

- name: Create directory for the code
  file:
    path: /brew
    owner: root
    group: root
    mode: '0644'
    state: directory

- name: Git checkout
  git:
    repo: "https://github.com/mohr-michael-adam/brew.git"
    dest: /brew

- name: Setup log directory
  file:
    path: /var/log/brew
    owner: root
    group: root
    mode: '0644'
    state: directory

- name: Slurp the pip requirements
  slurp:
    src: /brew/requirements.txt
  register: slurped_requirements

- name: Decode the pip requirements
  set_fact:
    raw_requirements: "{{ slurped_requirements['content'] | b64decode  }}"

- name: Parse newlines
  set_fact:
    requirements: "{{ raw_requirements.split('\n') }}"

- name: Install pip requirements
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items: "{{ requirements }}"

- name: Setup log rotate
  copy:
    dest: /etc/logrotate.d/brew
    src: logrotate
    owner: root
    group: root
    mode: 0600

- name: Create service
  debug:
    msg: "TODO - Create service"

- name: Restart service
  debug:
    msg: "TODO - Restart service"


